### ISSUE TITLE
Crash when trying to scroll through mod menu at all. Every time.

### ISSUE THREAD

**Issue by SethbotStar** [MrCrayfish/Catalogue#16]
https://pastebin.com/8TYhKFKd
Happens every time i try to scroll in the mods list.

**Comment by SethbotStar** [comment]
For now, i may just not use the mod until the issue is figured out... because i have no idea what it is.

**Comment by MrCrayfish** [comment]
It's currently Microblocks causing the issue from Code Chicken Lib. I am still investigating the issue.

**Comment by SethbotStar** [comment]
Alright... also, interestingly enough, i am no longer having the issue after i moved my modslist to the curseforge launcher... it's basically the same mods list, so i have no idea what issue it was having before. Still i do find it odd that it crashed in the first place, it should essentially just replace a gui, right? not sure if i should close this here, as i did stop having the issue for now, but i have no idea why, or what was causing it. You said it may be Microblocks, which is a dependency for Project Red... so i wouldn't be too happy to remove that. But i can try further testing on the other instance to see what's happening later.

Well, in the CF instance, Microblocks has no icon, which is odd.
![image](https://user-images.githubusercontent.com/30171402/144710004-2d0723e1-6a5b-4326-b5e0-453cce7812d9.png)
Tetra too:
![image](https://user-images.githubusercontent.com/30171402/144710054-94ac28ef-4fc3-4494-bdae-789f90abd5a5.png)

**Comment by mecwerks** [comment]
Also happens to me, but MrCrayfish's Gun Mod seems to break it. Removed the mod temporarily and it didn't crash while scrolling. https://pastebin.com/pQdxQZHa

**Comment by mecwerks** [comment]
Crash does not seem present in version 1.3.0 or earlier of Catalogue. 1.4.0 seems to be the first affected version.

**Comment by mrrpmrreeoow** [comment]
I have this crash too.
I think it's because of the icon, because the mod uses the obfuscate library (on the rendering item), so when you scroll there after turning on the game, it crashes, but not when the game is running, so the bug fix is for the mod to use the png icon and no item render.
