### ISSUE TITLE
Crash when trying to scroll through modlist.

### ISSUE THREAD

**Issue by Selsus74** [MrCrayfish/Catalogue#24]
Another mod causing a crash. Crash when the mod "Tome of Blood" is displayed. 
https://www.curseforge.com/minecraft/mc-mods/tome-of-blood

Crash Log: https://pastebin.com/SiDVKW9T

**Comment by Teebro88** [comment]
Have been experiencing the same issue. "Tome of Blood" triggering crash every time its supposed to scroll into view in the Catalogue mod list/menu

https://pastebin.com/tUT7YGxX

**Comment by MrCrayfish** [comment]
Fixed in cf41081d7c561c5a86bdb20dc0be584933d361de
This is for 1.18.2, I may do this for 1.16.5 too.

**Comment by magcicada** [comment]
yes 1.16.5 also need this fix, some mod will cause crash because of this issue, and the fix also can close #12.
