### ISSUE TITLE
Mod crashing game when opening the mods menu

### ISSUE THREAD

**Issue by McSquizzleswag** [MrCrayfish/Catalogue#27]
I have this mod in my modpack, using the only version available for 1.18.1, every time I click on the mods menu the display glitches and the game crashes, here is the crash log https://gist.github.com/McSquizzleswag/bfa651843d7773ebf78b363765fbaf9d

**Comment by MrCrayfish** [comment]
Fixed in cf41081d7c561c5a86bdb20dc0be584933d361de
Will be available for 1.18.2 so update as soon as you can.
