### ISSUE TITLE
Long config titles appear over config value

### ISSUE THREAD

**Issue by Mackzwellz** [MrCrayfish/Catalogue#3]
**Issue:** See screenshot:
![scr_2021-05-10_23-01-19](https://user-images.githubusercontent.com/15862948/117718178-6def6f00-b1e4-11eb-843e-5882a76bff5c.png)

Mod on screenshot: https://www.curseforge.com/minecraft/mc-mods/areas
Applicable for any mod, this one just has a good example of it. Enlarging the window does not resolve the issue (distance between config title and value is not increased, even though available screen space has increased)

**Suggestion for quick fix**: config value should be displayed over config title (i.e. config value sholud be "a layer above"/have such z-index so it shows up over title). 
Or, if config title is too long, excessive part of the string can be cut off. This is acceptable since we can check on-hover tooltip to see full config title.
**Suggestion for better fix**: change from quick fix + UI enhancements as seen in Cloth Config Config UI:
![scr_2021-05-10_23-21-56](https://user-images.githubusercontent.com/15862948/117720427-506fd480-b1e7-11eb-8407-d7ee0e55dd5f.png)

Great mods by the way, Forge needed this one and Configured for ages, thanks a lot.

**Comment by MrCrayfish** [comment]
Wrong mod repository
