### ISSUE TITLE
[Question] I wanna know why it looks so weird

### ISSUE THREAD

**Issue by qznfbnj** [MrCrayfish/Catalogue#31]
I'm using forge-1.18.2-40.1.52, I install 
1. catalogue-1.6.2-1.18.2
2. [Shimmer-forge-1.18.2-0.1.1](https://www.curseforge.com/minecraft/mc-mods/shimmer/files/3842485)
3. [rubidium-0.5.2a](https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3749094)
4. [rubidium_extras-1.18.2_v1.3.1](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras/files/3771366)

When I l click the mod list button, game will crash.

And many test:
catalogue + Shimmer + rubidium (without rubidium_extras) -> Can access mod list
catalogue + rubidium + rubidium_extras (without Shimmer) -> Can access mod list
Shimmer + rubidium + rubidium_extras (without catalogue) -> Can access mod list
catalogue + Shimmer + rubidium + rubidium_extras -> Crash (no crash-report generation, and [debug.log](https://gist.github.com/qznfbnj/a5ee85532562fd5d67deed359cf9a718), [latest.log](https://gist.github.com/qznfbnj/e8fe3b9f5fe8813edbd2aa8c242bb64e) or [logstream by launcher](https://gist.github.com/qznfbnj/31a921c28b54cd7b7e8e81589321317c) don't contains any useful information)

if I change rubidium_extras' mods.toml, delete '#' in '#issueTrackerURL':
catalogue + Shimmer + rubidium + rubidium_extras -> Can access mod list but version info of rubidium_extras become '0.0NONE'

I wanna know why it looks so weird and whose fault it is

**Comment by MrCrayfish** [comment]
Bug in Shimmer. Fixed as of https://github.com/Low-Drag-MC/Shimmer/issues/15 
Not sure if released yet though

**Comment by qznfbnj** [comment]
> Bug in Shimmer. Fixed as of [Low-Drag-MC/Shimmer#15](https://github.com/Low-Drag-MC/Shimmer/issues/15) Not sure if released yet though

This bug was submitted by me so I have tested the latest version (as is said above, Shimmer-forge-1.18.2-0.1.1) as soon as possible, and it has fixed in that 0.1.1 version. Do you mean Shimmer don't fix the bug completely?

**Comment by qznfbnj** [comment]
2) catalogue + Shimmer + rubidium + rubidium_extras -> Sometime can access mod list without crash, but GPU usage jump from 0% to 100% then jump from 100% to 0%.
![catalogue-2](https://user-images.githubusercontent.com/100760086/175801986-033bb5ed-ad3d-4b0f-9ff2-82ffe987fc52.jpg)
In this case, enter a world and exit to main screen, can access mod list without high GPU usage.

3) catalogue + Shimmer + rubidium + rubidium_extras -> Sometime can access mod list without high GPU usage, everything looks normal

Oh I seem to have found a workaround: use integrated graphics card instead of discrete graphics card to play Minecraft. At the cost of performance reduction, crash resolved. Although I don't know why.

**Comment by MrCrayfish** [comment]
Well all I can say is that uninstalling Shimmer solved the crash. Also not to mention Shimmer is patching vanilla rendering code, which is highly likely the cause of the issue. Thier code probably hasn't been tested on different graphics cards.
