### ISSUE TITLE
ScreenOpenEvent error with latest version of Forge

### ISSUE THREAD

**Issue by Gamemassa** [MrCrayfish/Catalogue#32]
MC Version: 1.19
Forge Version: 41.0.85

Hi,

I tried loading Minecraft with the latest version of Catalogue and I got a ScreenOpenEvent error. I've attached the crash report here.

[crash-2022-07-09_17.05.56-fml.txt](https://github.com/MrCrayfish/Catalogue/files/9077932/crash-2022-07-09_17.05.56-fml.txt)

**Comment by jellybean13** [comment]
Affected classes: https://github.com/MrCrayfish/Catalogue/blob/1.19.X/src/main/java/com/mrcrayfish/catalogue/client/ClientHandler.java#L17

**Comment by MrCrayfish** [comment]
Fixed in 1.6.3
