### ISSUE TITLE
Filter mods by actually having a config

### ISSUE THREAD

**Issue by Xetaxheb** [MrCrayfish/Catalogue#37]
A toggle like 'show only mods with updates' except for 'show only mods with configuration'. 
Aka: any that would enable the Config button. Doesn't seem that long to parse.

Another useful thought: Filtering for 'show only mods with non-default settings'.
Aka: any that would have an entry 'reset all' or 'reset'.

**Comment by MrCrayfish** [comment]
Thanks for the suggestion. Added in https://github.com/MrCrayfish/Catalogue/commit/15265572a4af1c5b042c3d3b31eaa5e4325bb06f
