### ISSUE TITLE
Config option to replace Realms button

### ISSUE THREAD

**Issue by CapoFantasma97** [MrCrayfish/Catalogue#40]
See above. When playing non-semivanilla modpacks, the game's incompatible with Realms anyways.

**Comment by MrCrayfish** [comment]
Fabric can play on vanilla servers and Realms (if using latest version of MC), and client only mods can be used (like Catalogue). So replacing the button is not a good idea. As a recent versions, you can now change the position of the mods button.

**Comment by CapoFantasma97** [comment]
Mod Menu for Fabric has multiple options for this, being as default a full size button under Realms, but also giving the options to either make them both half size next to esch other, or even replace the Realms button entirely. 

This is useful for modpack makers, and users who like to manually adjust mods and want a cleaner interface. It hasn't created problems to date, so it could be a good idea.
