### ISSUE TITLE
Feature Request: Remember Last Search 

### ISSUE THREAD

**Issue by gigawhip** [MrCrayfish/Catalogue#45]
When editing a mod's config, it's often required to tweak the config, close the menu, interact with the game a little, then go back into the menu and tweak the config further. When you open the menu to go back the make further edits, you have to type the name of the mod you're configuring again each time because the search bar doesn't remember the most recent entry. If onerous, this feature could be togglable.

**Comment by MrCrayfish** [comment]
Thanks for the suggestion. I've added the feature in 3fcc8edd021033cb03c15584d7fbb9836070cdc6
