### ISSUE TITLE
[1.19.4] Game crashed after clicking "Mods" button

### ISSUE THREAD

**Issue by jellybean13** [MrCrayfish/Catalogue#47]
Description: Client crashed after clicking "Mods" button on the main menu.
Minecraft version: 1.19.4
Mod loader: Forge
Mod loader version: 1.19.4-45.0.40
Catalogue version: 1.7.0-1.19.3
Mod list: Catalogue
Logs (client): https://pastebin.com/cJsnRX91

**Comment by MrCrayfish** [comment]
1.19.3 version is not compatible with 1.19.4

**Comment by jellybean13** [comment]
> 1.19.3 version is not compatible with 1.19.4

However, this mod doesn't have 1.19.4 version.
