### ISSUE TITLE
Suggestion: Filter for mods which are dependencies

### ISSUE THREAD

**Issue by Ezeyra** [MrCrayfish/Catalogue#48]
As the title says. Would be cool if you could add a filter to only show mods which are depended on by other mods, and maybe also which mods depend on them.

**Comment by MrCrayfish** [comment]
Thanks for the suggestion. In an upcoming version for Minecraft 1.21.1, you can now show dependencies and dependents for each mod.
![image](https://github.com/user-attachments/assets/41eba320-7748-4d4e-8861-26e2ab7f943f)
