### ISSUE TITLE
Would you consider posting your mods to Modrinth as well as Curseforge?

### ISSUE THREAD

**Issue by rhysdh540** [MrCrayfish/Catalogue#49]
curseforge is going through some weird stuff right now (not really sure what, seems to be some concerns about privacy and their handling of user's data, but people seem to not like it now)

also modrinth has an actually working maven so that's cool when I want to add your mods to my dev environment

thanks

**Comment by MenacingPerson** [comment]
@MrCrayfish I don't think this was completed? I don't see it anywhere on modrinth.

**Comment by Yarden-zamir** [comment]
Hello? please don't forget about us modrinth folk, we also enjoy you mods ):

**Comment by lonevox** [comment]
@MrCrayfish This still isn't on Modrinth. Any chance it could be added?

**Comment by vaporvee** [comment]
@MrCrayfish why can't you at least answer why are you so rude and are ignoring us

**Comment by vaporvee** [comment]
can i at least get approval to use it for a modrinth modpack
