### ISSUE TITLE
Attempt to edit config files for mods crashes game

### ISSUE THREAD

**Issue by CephalonAxii** [MrCrayfish/Catalogue#50]
I downloaded this so help with changing config files while in game, but when I attempt to do so it causes the game to crash. In my most recent attempt it was with Ice and Fire 1.18.2 mod. Below is the crash repor. If we need to send it a different way, please let me  know. 
[crash-2023-05-02_15.31.06-client.txt](https://github.com/MrCrayfish/Catalogue/files/11377530/crash-2023-05-02_15.31.06-client.txt)

**Comment by MrCrayfish** [comment]
This is a Configured issue, not Catalogue.
