### ISSUE TITLE
Suggestion: Hide ModMenu's Mods button when installed

### ISSUE THREAD

**Issue by shizotoaster** [MrCrayfish/Catalogue#51]
ModMenu is required for Menulogue to work but it is causing two differrent mods to appear in title screen. I suggest adding an option to hide or replace ModMenu's Mods button
![image](https://user-images.githubusercontent.com/51480483/235914075-37629e7c-75f3-41ae-98c1-faffc585e8a1.png)

It would also be very nice to have a text button instead of icon, just like in Catalogue for Forge
Fabric:
![image](https://user-images.githubusercontent.com/51480483/235913426-ba9c529f-c1de-4106-ab8e-a302579c3e94.png)
Forge:
![image](https://user-images.githubusercontent.com/51480483/235913815-4638c226-c194-4fee-983b-2b39a61638db.png)

**Comment by MrCrayfish** [comment]
Why are you installing them together?

**Comment by MrCrayfish** [comment]
If you install them together, that's just how it's going to be. Just remove mod menu if you don't want the other button. As for the text button, that is Forge, not Catalogue.

**Comment by shizotoaster** [comment]
ModMenu is Menulogue's dependency, I can't remove it
![image](https://user-images.githubusercontent.com/51480483/236049117-c566d080-19d6-4db3-9ce3-1253ef1d916a.png)

**Comment by shizotoaster** [comment]
> As for the text button, that is Forge, not Catalogue.

So why there's no Catalogue Mods button near standard Mods button in Forge?

**Comment by MrCrayfish** [comment]
In regards to the modmenu being a dependency in Menulogue, that is my mistake. I will push a fix.

As for the `Mods` button, Forge adds that button and Catalogue just overrides the press function to open it's screen instead. Since Fabric doesn't have a `Mods` button, I add my own button and for compatibility sake, replacing/removing existing widgets is avoided.

**Comment by MrCrayfish** [comment]
Update is now available on CurseForge
https://www.curseforge.com/minecraft/mc-mods/menulogue/files/4522176
