### ISSUE TITLE
incompat with aether (1.19.2) [fixed]

### ISSUE THREAD

**Issue by No1129** [MrCrayfish/Catalogue#59]
catalogue's updated mod menu does not show with aether loaded
![2023-09-10_19 39 29](https://github.com/MrCrayfish/Catalogue/assets/133806873/a5967b3b-cfd0-41cf-8618-65159bce9dcf)
logs:
[latest.log](https://github.com/MrCrayfish/Catalogue/files/12579639/latest.log)
[debug.log](https://github.com/MrCrayfish/Catalogue/files/12579640/debug.log)

**Comment by QboiDev** [comment]
~~From what I see in the logs, there seems to be references to mods that don't exist...~~
What was I thinking here lmao :rofl:

**Comment by No1129** [comment]
oh cool they fixed it
