### ISSUE TITLE
[Suggestion/Request] Better Button

### ISSUE THREAD

**Issue by itsMarkiS** [MrCrayfish/Catalogue#63]
make an option so we can decide where the button of the mod list will be located, just like the mod menu for example
i use both mod menu and catalogue together with the compatibility version, and i, personally like catalogue more, but the button in mod menu is way more practical and also doesnt conflicts with other mod stuffs i use

for example, origin enhanced, a mod designed for origin realms server, has a button in the same place as catalogue one

**Comment by MrCrayfish** [comment]
Thanks for the suggestion. I've added it in 9af7f838ac749120c5fcbd3482cfda064747e787
