### ISSUE TITLE
ESC Key Takes you out of all menus

### ISSUE THREAD

**Issue by DereC4** [MrCrayfish/Catalogue#64]
Could the escape key (ESC) be changed to only go back a page? Right now on the main menu, whenever I toggle mod configs, hitting esc takes me all the way out when I would simply like to go back a page.

Could this be added as a toggle perhaps? Having to rely on the back button is a bit more inconvenient.

**Comment by MrCrayfish** [comment]
Config screens have nothing to do with Catalogue. It's just a mod list screen
