### ISSUE TITLE
Incompatible with Xaero's Minimap

### ISSUE THREAD

**Issue by Bliss-tbh** [MrCrayfish/Catalogue#69]
When using Xaeros's Minimap, Minecraft reverts back to the default mod menu which is a problem as it's a 'quite a popular' mod. (:
I'm pretty sure that's what #68 was talking about.

**Comment by MrCrayfish** [comment]
Downgrade Xaero's, they changed something that is causing the issue. Their mod is also closed source so I can't help with this issue.
