### ISSUE TITLE
[1.17.X] Crash when hovering over mod id

### ISSUE THREAD

**Issue by Autovw** [MrCrayfish/Catalogue#7]
When hovering the mouse over a mod id the game chrashes. (See the video I recorded in dev environment)

https://user-images.githubusercontent.com/68228006/130355235-c580918f-ecdb-4560-ace6-37456675609e.mp4

Crash only occurs on 1.17, also outside of dev environment. 1.16 is fine.

[Crashlog for more detail](https://gist.github.com/Autovw/ed629cabaaed6ace29d9e9b0260356af)
(Crashlog taken outside of dev environment)

**Comment by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET** [comment]
Tested, also crashes for me

**Comment by Minecraftschurli** [comment]
can Verify (happens when using it as runtime mod in another dev env)
