### ISSUE TITLE
crash-menulogue-fabric-1.20.1-1.0.4

### ISSUE THREAD

**Issue by zc1108aaa** [MrCrayfish/Catalogue#74]
[crash-2024-09-03_05.02.56-client.txt](https://github.com/user-attachments/files/16841262/crash-2024-09-03_05.02.56-client.txt)
0
[latest.log](https://github.com/user-attachments/files/16841263/latest.log)

**Comment by MrCrayfish** [comment]
Overloaded Armor Bar is providing an invalid screen due to old version of [GBfabrictools](https://github.com/gbl/GBfabrictools).
Going to close on my end since it's not due to my mod and [GBfabrictools](https://github.com/gbl/GBfabrictools) is now archived.,
